spring:
  application:
    name: oficinaBackend

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:admin@localhost:27017/oficina_db?authSource=admin}
      auto-index-creation: true

  jackson:
    serialization:
      indent-output: true

itau:
  ssl:
    key-store: ${ITAU_SSL_KEY_STORE:}
    key-store-password: ${ITAU_SSL_KEY_STORE_PASSWORD:}
  mtls:
    enabled: ${ITAU_MTLS_ENABLED:false}
  url-auth: ${ITAU_URL_AUTH:https://devportal.itau.com.br/api/jwt}
  url-api: ${ITAU_URL_API:https://devportal.itau.com.br/sandboxapi/cash_management_ext_v2/v2/boletos}
  url-query: ${ITAU_URL_QUERY:https://devportal.itau.com.br/sandboxapi/cash_management_ext_v2/v2/boletos}
  scope: ${ITAU_SCOPE:}
  sandbox-token: ${ITAU_SANDBOX_TOKEN:}
  mock-mode: ${ITAU_MOCK_MODE:false}


api:
  security:
    secret-key: "ba8d60a2323abe49ec8813f01ea6ea82eaff6f76f14caac64a022662f9844eec"
